/*
 * File: app/view/DescriptionForm.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DescriptionForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.descriptionform',

    border: 'false',
    height: 109,
    id: 'descriptionForm',
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    bodyBorder: false,
    url: 'equation-description',
    'border-style': '',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            url: 'equation-description'
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    border: 'false',
                    frame: true,
                    width: 618,
                    layout: {
                        type: 'fit'
                    },
                    title: 'Graph Description',
                    flex: 1,
                    items: [
                        {
                            xtype: 'textareafield',
                            frame: false,
                            height: 43,
                            hidden: false,
                            id: 'description',
                            margin: '',
                            padding: '',
                            width: 579,
                            name: 'description',
                            readOnly: true,
                            fieldLabel: ''
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});