/*
 * File: app/view/GraphPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.GraphPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.GraphPanel',

    id: '',
    maxWidth: 300,
    minWidth: 100,
    padding: '',
    width: 150,
    layout: {
        type: 'anchor'
    },
    collapsible: true,
    minButtonWidth: 20,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    border: '',
                    html: '<embed id=\'svg\' src=\'data/setup.svg\' width=\'600\' height=\'800\' />',
                    id: 'graph',
                    padding: '',
                    anchor: '0, 0'
                },
                {
                    xtype: 'container',
                    id: 'audio',
                    anchor: '0, 0'
                }
            ]
        });

        me.callParent(arguments);
    }

});