/*
 * File: app/view/MathTraxView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MathTraxView', {
    extend: 'Ext.container.Viewport',
    requires: [
        'MyApp.view.DescriptionForm'
    ],

    id: 'MathTraxView',
    padding: 5,
    autoScroll: true,
    resizable: 'DescriptionPanel, SettingPanel, GraphPanel',
    layout: {
        type: 'border'
    },
    collapsible: 'true',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    id: 'DescriptionPanel',
                    padding: '',
                    bodyPadding: 5,
                    activeTab: 0,
                    flex: 1,
                    margins: '0 0 0 0',
                    region: 'center',
                    items: [
                        {
                            xtype: 'panel',
                            height: 500,
                            width: 313,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            title: 'Equation',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    maxHeight: 60,
                                    padding: '5px',
                                    width: 336,
                                    layout: {
                                        type: 'absolute'
                                    },
                                    title: 'Enter Your Equation',
                                    flex: 1,
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            id: 'equation',
                                            name: 'equation',
                                            fieldLabel: '',
                                            emptyText: 'Please enter an equation',
                                            enableKeyEvents: true,
                                            autoSelect: false,
                                            displayField: 'name',
                                            store: 'equationStore',
                                            valueField: 'id',
                                            anchor: '100%',
                                            listeners: {
                                                keydown: {
                                                    fn: me.onEquationKeydown,
                                                    scope: me
                                                },
                                                select: {
                                                    fn: me.onEquationSelect,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'descriptionform',
                                    flex: 1
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 308,
                            width: 377,
                            title: 'Data',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    height: 62,
                                    padding: '',
                                    title: 'Load Your Data File',
                                    items: [
                                        {
                                            xtype: 'filefield',
                                            margin: '',
                                            padding: 5,
                                            width: 321,
                                            fieldLabel: '',
                                            anchor: '95%'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    height: 259,
                                    title: 'View Your Data',
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: '',
                                            boxLabel: 'Box Label',
                                            checked: true,
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            height: 213,
                                            padding: '',
                                            autoScroll: true,
                                            bodyPadding: '',
                                            title: 'My Grid Panel',
                                            store: 'dataFileStore',
                                            viewConfig: {

                                            },
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'x',
                                                    text: 'X'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'y',
                                                    text: 'Y'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Physics'
                        },
                        {
                            xtype: 'panel',
                            height: 319,
                            width: 558,
                            title: 'Information'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 150,
                    id: 'SettingPanel',
                    maxHeight: 200,
                    minHeight: 150,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    collapsible: true,
                    flex: 1,
                    margins: '5 0 0 0',
                    region: 'south',
                    split: false
                },
                {
                    xtype: 'panel',
                    id: 'GraphPanel',
                    maxWidth: 300,
                    minWidth: 100,
                    width: 150,
                    collapsible: true,
                    minButtonWidth: 20,
                    flex: 1,
                    margins: '0 0 0 5',
                    region: 'east',
                    split: false
                },
                {
                    xtype: 'panel',
                    height: 198,
                    hidden: false,
                    id: 'TopPanel',
                    collapsed: true,
                    title: 'MathTrax',
                    titleCollapse: false,
                    flex: 1,
                    region: 'north'
                }
            ]
        });

        me.callParent(arguments);
    },

    onEquationKeydown: function(textfield, e, options) {
        if(e.getCharCode() == e.ENTER) {
            Ext.getCmp('descriptionForm').getForm().load({   
                method: 'GET',
                url: 'equation-description',
                params: {equation:textfield.getRawValue()},
                failure: function() {
                    Ext.Msg.alert('Error', 'Unable to load form data');
                },
                waitMsg: 'Retrieving form data',
                waitTitle: 'Loading...'
            }); 
        }
    },

    onEquationSelect: function(combo, records, options) {
        //Ext.ModelMgr.getModel('EquationDescModel').load(1, {
        //    params: {equation:combo.getValue()},
        //    success: function(eqDescription) {
        //        combo.container.down('#descriptionform').loadRecord(eqDescription);
        //    }
        //});

        Ext.getCmp('descriptionForm').getForm().load({   
            method: 'GET',
            url: 'equation-description',
            params: {equation:combo.getRawValue()},
            failure: function() {
                Ext.Msg.alert('Error', 'Unable to load form data');
            },
            waitMsg: 'Retrieving form data',
            waitTitle: 'Loading...'
        });
    }

});