/*
 * File: app/view/MathTraxView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MathTraxView', {
    extend: 'Ext.container.Viewport',
    requires: [
        'MyApp.view.MyFileUpload'
    ],

    id: 'MathTraxView',
    padding: 5,
    autoScroll: true,
    resizable: 'DescriptionPanel, SettingPanel, GraphPanel',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    id: 'DescriptionPanel',
                    padding: '',
                    bodyPadding: 5,
                    activeTab: 1,
                    flex: 1,
                    margins: '0 0 0 0',
                    region: 'center',
                    items: [
                        {
                            xtype: 'form',
                            id: 'equationTab',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            bodyPadding: 10,
                            title: 'Equation',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    maxHeight: 60,
                                    padding: '5px',
                                    width: 336,
                                    layout: {
                                        type: 'absolute'
                                    },
                                    title: 'Enter Your Equation',
                                    flex: 1,
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            id: 'equation',
                                            name: 'equation',
                                            fieldLabel: '',
                                            emptyText: 'Please enter an equation',
                                            enableKeyEvents: true,
                                            autoSelect: false,
                                            displayField: 'name',
                                            store: 'equationStore',
                                            valueField: 'id',
                                            anchor: '100%',
                                            listeners: {
                                                keydown: {
                                                    fn: me.onEquationComboKeydown,
                                                    scope: me
                                                },
                                                select: {
                                                    fn: me.onEquationComboSelect,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    height: 51,
                                    id: 'params',
                                    width: 252,
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    title: 'Change Your Equation Settings'
                                },
                                {
                                    xtype: 'fieldset',
                                    border: 'false',
                                    frame: true,
                                    width: 618,
                                    autoScroll: false,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    title: 'Graph Description',
                                    flex: 1,
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            height: 203,
                                            hidden: false,
                                            id: 'description',
                                            margin: '',
                                            width: 225,
                                            name: 'description',
                                            readOnly: true,
                                            fieldLabel: '',
                                            flex: 1
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            id: 'dataTab',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            title: 'Data',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    height: 54,
                                    padding: '',
                                    title: 'Load Your Data File',
                                    items: [
                                        {
                                            xtype: 'myfileupload',
                                            anchor: '95%'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    height: 259,
                                    id: 'grid',
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    title: 'View Your Data',
                                    flex: 1
                                },
                                {
                                    xtype: 'fieldset',
                                    frame: false,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    title: 'Graph Description',
                                    flex: 1,
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            id: 'description',
                                            flex: 1
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Physics'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 150,
                    id: 'SettingPanel',
                    maxHeight: 200,
                    minHeight: 150,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    collapsible: true,
                    flex: 1,
                    margins: '5 0 0 0',
                    region: 'south',
                    split: false
                },
                {
                    xtype: 'panel',
                    id: 'GraphPanel',
                    maxWidth: 300,
                    minWidth: 100,
                    width: 150,
                    collapsible: true,
                    minButtonWidth: 20,
                    flex: 1,
                    margins: '0 0 0 5',
                    region: 'east',
                    split: false
                },
                {
                    xtype: 'panel',
                    height: 198,
                    hidden: false,
                    id: 'TopPanel',
                    collapsed: true,
                    title: 'MathTrax',
                    titleCollapse: false,
                    flex: 1,
                    region: 'north'
                }
            ]
        });

        me.callParent(arguments);
    },

    onEquationComboKeydown: function(textfield, e, options) {
        if(e.getCharCode() == e.ENTER) {
            Ext.getCmp('equationTab').getForm().load({   
                method: 'GET',
                url: 'equation-description',
                params: {equation:textfield.getRawValue()},
                failure: function() {
                    Ext.Msg.alert('Error', 'Unable to load form data');
                },
                waitMsg: 'Retrieving form data',
                waitTitle: 'Loading...'
            }); 
        }
    },

    onEquationComboSelect: function(combo, records, options) {
        Ext.getCmp('equationTab').getForm().load({   
            method: 'GET',
            url: 'equation-description',
            params: {equation:combo.getRawValue()},
            success: function(fp, o){
                var fieldset = Ext.getCmp('params');
                fieldset.removeAll();
                var params = o.result.data.params;
                for(var p in params){
                    fieldset.add({
                        xtype: 'textfield',
                        fieldLabel: p,
                        value: params[p],
                        maxHeight: 20,
                        maxWidth: 80,
                        labelWidth: 30,                
                        flex: 1
                    });
                }
            },
            failure: function() {
                Ext.Msg.alert('Error', 'Unable to load form data');
            },
            waitMsg: 'Retrieving form data',
            waitTitle: 'Loading...'
        });
    }

});